# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'trip_config.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(681, 342)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout = QtWidgets.QGridLayout(self.tab)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.lineEdit_trippath = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_trippath.setObjectName("lineEdit_trippath")
        self.gridLayout.addWidget(self.lineEdit_trippath, 2, 1, 1, 2)
        self.pushButton_browsetrippath = QtWidgets.QPushButton(self.tab)
        self.pushButton_browsetrippath.setObjectName("pushButton_browsetrippath")
        self.gridLayout.addWidget(self.pushButton_browsetrippath, 2, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 0, 0, 1, 1)
        self.lineEdit_server = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_server.setObjectName("lineEdit_server")
        self.gridLayout_4.addWidget(self.lineEdit_server, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(245, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem, 0, 2, 2, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 1, 0, 1, 1)
        self.lineEdit_username = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_username.setObjectName("lineEdit_username")
        self.gridLayout_4.addWidget(self.lineEdit_username, 1, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 2, 0, 1, 1)
        self.lineEdit_password = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.gridLayout_4.addWidget(self.lineEdit_password, 2, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem1, 3, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 3, 0, 1, 5)
        self.comboBox = QtWidgets.QComboBox(self.tab)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout.addWidget(self.comboBox, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.lineEdit_wdir = QtWidgets.QLineEdit(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_wdir.sizePolicy().hasHeightForWidth())
        self.lineEdit_wdir.setSizePolicy(sizePolicy)
        self.lineEdit_wdir.setObjectName("lineEdit_wdir")
        self.gridLayout.addWidget(self.lineEdit_wdir, 0, 1, 1, 2)
        self.pushButton_browsewdir = QtWidgets.QPushButton(self.tab)
        self.pushButton_browsewdir.setObjectName("pushButton_browsewdir")
        self.gridLayout.addWidget(self.pushButton_browsewdir, 0, 3, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 0, 4, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_8 = QtWidgets.QLabel(self.tab_2)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 0, 0, 1, 2)
        self.comboBox_2 = QtWidgets.QComboBox(self.tab_2)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_2, 0, 2, 1, 1)
        self.comboBox_3 = QtWidgets.QComboBox(self.tab_2)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_3, 0, 3, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 0, 4, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.tab_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 1, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(471, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem4, 1, 2, 1, 3)
        self.label_9 = QtWidgets.QLabel(self.tab_2)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 3, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.tab_2)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 5, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem5, 7, 0, 1, 1)
        self.pushButton_browsesis = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_browsesis.setObjectName("pushButton_browsesis")
        self.gridLayout_2.addWidget(self.pushButton_browsesis, 6, 3, 1, 1)
        self.lineEdit_ddd = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_ddd.setObjectName("lineEdit_ddd")
        self.gridLayout_2.addWidget(self.lineEdit_ddd, 2, 0, 1, 3)
        self.lineEdit_spc = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_spc.setObjectName("lineEdit_spc")
        self.gridLayout_2.addWidget(self.lineEdit_spc, 4, 0, 1, 3)
        self.pushButton_browsespc = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_browsespc.setObjectName("pushButton_browsespc")
        self.gridLayout_2.addWidget(self.pushButton_browsespc, 4, 3, 1, 1)
        self.pushButton_browseddd = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_browseddd.setObjectName("pushButton_browseddd")
        self.gridLayout_2.addWidget(self.pushButton_browseddd, 2, 3, 1, 1)
        self.lineEdit_sis = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_sis.setObjectName("lineEdit_sis")
        self.gridLayout_2.addWidget(self.lineEdit_sis, 6, 0, 1, 3)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_11 = QtWidgets.QLabel(self.tab_3)
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 0, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(359, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem6, 0, 1, 1, 2)
        self.lineEdit_hlut = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_hlut.setObjectName("lineEdit_hlut")
        self.gridLayout_3.addWidget(self.lineEdit_hlut, 1, 0, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(274, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem7, 1, 2, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.tab_3)
        self.label_12.setObjectName("label_12")
        self.gridLayout_3.addWidget(self.label_12, 2, 0, 1, 1)
        self.lineEdit_dedx = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_dedx.setObjectName("lineEdit_dedx")
        self.gridLayout_3.addWidget(self.lineEdit_dedx, 3, 0, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(20, 137, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem8, 4, 0, 1, 1)
        self.pushButton_browsehlut = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_browsehlut.setObjectName("pushButton_browsehlut")
        self.gridLayout_3.addWidget(self.pushButton_browsehlut, 1, 1, 1, 1)
        self.pushButton_browsededx = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_browsededx.setObjectName("pushButton_browsededx")
        self.gridLayout_3.addWidget(self.pushButton_browsededx, 3, 1, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "TRiP98 install"))
        self.pushButton_browsetrippath.setText(_translate("Dialog", "Browse"))
        self.label_2.setText(_translate("Dialog", "Working dir"))
        self.groupBox.setTitle(_translate("Dialog", "Remote"))
        self.label_4.setText(_translate("Dialog", "Server IP/Hostname"))
        self.label_5.setText(_translate("Dialog", "Username"))
        self.label_6.setText(_translate("Dialog", "Password"))
        self.comboBox.setItemText(0, _translate("Dialog", "Local"))
        self.comboBox.setItemText(1, _translate("Dialog", "Remote"))
        self.label_3.setText(_translate("Dialog", "TRiP98 path"))
        self.pushButton_browsewdir.setText(_translate("Dialog", "Browse"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "Access"))
        self.label_8.setText(_translate("Dialog", "Projectile and ripple filter"))
        self.comboBox_2.setItemText(0, _translate("Dialog", "H-1"))
        self.comboBox_2.setItemText(1, _translate("Dialog", "He-4"))
        self.comboBox_2.setItemText(2, _translate("Dialog", "C-12"))
        self.comboBox_2.setItemText(3, _translate("Dialog", "O-16"))
        self.comboBox_2.setItemText(4, _translate("Dialog", "Ne-20"))
        self.comboBox_3.setItemText(0, _translate("Dialog", "0 mm RiFi"))
        self.comboBox_3.setItemText(1, _translate("Dialog", "3 mm RiFi"))
        self.label_7.setText(_translate("Dialog", "DDD Directory"))
        self.label_9.setText(_translate("Dialog", "SPC Directory"))
        self.label_10.setText(_translate("Dialog", "SIS File (optional)"))
        self.pushButton_browsesis.setText(_translate("Dialog", "Browse"))
        self.pushButton_browsespc.setText(_translate("Dialog", "Browse"))
        self.pushButton_browseddd.setText(_translate("Dialog", "Browse"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Kernel files"))
        self.label_11.setText(_translate("Dialog", "Hounsfield lookup table (HLUT)"))
        self.label_12.setText(_translate("Dialog", "Stopping power table (dE/dx)"))
        self.pushButton_browsehlut.setText(_translate("Dialog", "Browse"))
        self.pushButton_browsededx.setText(_translate("Dialog", "Browse"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Dialog", "Lookup tables"))

