import logging

logger = logging.getLogger(__name__)


class KernelModel(object):
    """
    Kernel data, holding all necessary data for a certain projectile
    """

    projectile_z = 0
    projectilz_a = 0
    projectile_iupac = ""  # chemical symbol (parsed by TRiP), "H", "He", "C", "O", "Ne" ....
    projectile_name = ""  # cleartext name "Protons", "Carbon-12 ions", "Antiprotons", ...
    rifi_name = ""  # name of ripple filter, e.g. "3 mm Rifi", for documentation only
    rifi_thickness = ""
    ddd_path = ""  # "/local/trip/data/ddd/*"
    spc_path = ""  # "/local/trip/data/spc/*"
    sis_table = ""  # if none, it will be autogenerated
    comment = ""  # arbitrary text

    def __init__(self):
        pass
