# before committing check this file here: https://lint.travis-ci.org/

language: python

# travis-ci runs by default Ubuntu 16.04 (xenial)
sudo: false
dist: xenial

# testing pyqt5 apps require X server
addons:
  apt:
    update: true
    packages:
    - xvfb
    - xfonts-100dpi
    - xfonts-75dpi
    - xorg
    - dbus-x11
    - xfonts-cyrillic

matrix:
    include:
        - os: linux
          python: 3.7
          env: TOXENV=packaging
        - os: linux
          python: 3.5
          env: TOXENV=py35
        - os: linux
          python: 3.6
          env: TOXENV=py36
        - os: linux
          python: 3.7
          env: TOXENV=py37
        - os: linux
          python: 3.7
          env: TOXENV=coverage
##    uncomment and adjust if you want to allow some failures
    allow_failures:
        - os: linux
          python: 3.8
          env: TOXENV=py38

install:
  - pip install --only-binary PyQt5 -r requirements.txt
  - pip install -r tests/requirements-test.txt


script:
  - tox --recreate --notest && tox
  - if [[ "$TRAVIS_TEST_RESULT" == "0" ]] && [[ $TOXENV == "packaging" ]]; then .travis/check_package_deploy.sh; fi

deploy:
 - provider: pypi # upload pip package to pypi https://docs.travis-ci.com/user/deployment/pypi/
    user: grzanka
    distributions: sdist bdist_wheel
    skip_cleanup: true
    skip_upload_docs: true
    password:
      secure: kmwue5PN2Yi+JpdGQs+/pnoRvNsmjnvbLCHSZWJBrR5A+DPR6/E4bs5r9RZxSlBT5tOtpf+Fekbk3jNwN9p+Dr5tBaDG2GdVbqo/vMsmw0MguZUK34+RFrC0v38ovwRY69O6owEVYZeu2YZgq6PZT20n/OSsQn+Ep7YBYCVjLnG+k49JcfBgMEX/p0aVTcFz2gicrrxlvcyiKW7EMSjSrpgmj1XjEw5l2NCOoXyEtTiIBfGruw9X0aN78jq1eX4E893NfY4zk2sK6pMDq0B3SagsOeufGnMtVjYxct34vRQlNtBonh7GZHOh95NPTFT5Md5HY0vibOKv8/MjzRjLQrlRxoMjm3lZflAwKYldE5GSbpZQPxx3X7DIGZY2Lo1DcGoxx6c8BiHaVhBi7ardMg84ItwSQtTcw1XTPXStYhNQwe9lqoFhfHKD2pfsSs2BGbzUeE6TsXKQrCs9c0lNaE2guuwTqUxWEIv4MC4svqGmLjTRyQDyyIh6fiBCIPlOGHs2XlMixiy+sRUXyr5YYILOTu8WNdA/UgqOAXkTvgzPomWVIFpZvS3lFASho4yW2iNUcrrWQHoEJiIODwOQWhqY4NpVRzfft07zFEiIWXXWZ8bNbGgztUtXiotv2YH5nwQgl38jMeCEX1qQz16NGGOS23ubbxpAbUE/8Ia5Ca0=
    on:
      repo: DataMedSci/pymchelper
      tags: true
      condition: $TOXENV == "packaging" && "$TRAVIS_TEST_RESULT" == "0"
