# before committing check this file here: https://lint.travis-ci.org/

language: python

os: linux

# travis-ci runs by default Ubuntu 16.04 (xenial)
dist: bionic
sudo: false

# testing pyqt5 apps require X server
addons:
  apt:
    update: true
    packages:
    - xvfb
    - xfonts-100dpi
    - xfonts-75dpi
    - xorg
    - dbus-x11
    - xfonts-cyrillic
    - libxkbcommon-x11-0

jobs:
    include:
        - os: linux
          python: 3.7
          env: TOXENV=packaging
        - os: linux
          python: 3.5
          env: TOXENV=py35
        - os: linux
          python: 3.6
          env: TOXENV=py36
        - os: linux
          python: 3.7
          env: TOXENV=py37
        - os: linux
          python: 3.8
          env: TOXENV=py38
        - os: linux
          python: 3.7
          env: TOXENV=coverage
##   uncomment and adjust if you want to allow some failures
#    allow_failures:
#        - os: linux
#          python: 3.8
#          env: TOXENV=py38

install:
  - pip install pip --upgrade
  - pip -V
  - pip install --only-binary PyQt5 -r requirements.txt
  - pip install -r tests/requirements-test.txt
  - apt list --installed


script:
  - tox --recreate --notest && tox
  - if [[ "$TRAVIS_TEST_RESULT" == "0" ]] && [[ $TOXENV == "packaging" ]]; then .travis/check_package_deploy.sh; fi


deploy:
  provider: pypi # upload pip package to pypi https://docs.travis-ci.com/user/deployment/pypi/
  username: "__token__"
  password:
    secure: "bzkLilL3/6sgCIqJtlbdUKQbzNteBXkjzkjkRoSfslqgnYH7aqRQeyjSlzMhuJPnH8AQ5UkDiA+hd/h+YYHizHcwYRzy5URkDcwICGjPv8InqwrV54IJq+fD1HmkKxTNMdk/LFWy1utioEvUKKY5QvVc4sswv2M8tHnga6h60KPHoEe4OHxJazXMKgr/28vLxfd4kk9W9gYcx6fm7VbUEPkGG/W9oFIREF33V99jPAalS+soetD1BGIhHEPVaviGdOVszoMT9skOZ+7CDXGGOUZyGJNHZjZOHQhoOFULG1wWQivbSmwvSG0rLTrnxrOR1yT99EOPY3FMNHpgQzsYA/mCDNje5ZXQDrcHWDmkGeKplA8JwPOZQg0bdMhn8WWAXUcfsVtud6HoYSyZoFHoGNLdp17HzP9gY//uFrtY36/z/k/TynnCQnukanZODXL7CXHW4wQBtuu6/JEpzU5F3o6mOVXZ6uVucJK6p1ZcszDwXqriR2e5LWsyJh3po1XNnplQIioTzjwje7zLjt176+aLj2B2v8/I1C3AuVPK33ZFiI/QiPvNpbcwGOy4PiIwUxDSX2d4i8104ytOmsav2kfu95Ef42rlTrQW5nrdaa0jgdTvLzTi3eyQM+4oLCMZtmFBo5VoFswN0zH6nHkz6RbmeAR05U6XlLq1RxRZqE0="
  distributions: "sdist bdist_wheel"
  cleanup: true
  upload_docs: false
  on:
    repo: pytrip/pytripgui
    tags: true
    condition: $TOXENV == "packaging" && "$TRAVIS_TEST_RESULT" == "0"