# before committing check this file here: https://lint.travis-ci.org/
language: generic

env:
  global:
    - PYPIUSER=grzanka
    #  pypi secured password (PYPIPASS variable), you need to update it to your own if you want to use it
    - secure: "SMZG9NowpZXGR0uNh5FvTRNO/rafNlj5smen8GK77tgYP8AiCjoXxzl5EXhO8WRd/6Zf1vMtSan8p0fif/8LCr7hncZ8SZ/rKNnf1EOKa0Wam7TVxwVaeMnThDyZNOuV5/3/NDEg/ro194Z7kKHGPAaE8GycaGxAmXG8EbCIVw8uYu3DHDstpewWveGusKqPFOUORUHtfEdpINMizY/Ady34BDRRC7UHU67eWGx3wa1g5WXBr34LKQTHY8nzWI6W04z55gQhHWytrJbp947/JvMItSEOd3s09KPv36K4nezbMrpnWmhSxtP9JDhZI2eLO3bjQHWRnoYNBG2DN/6VC0C+eUsZ81Pi17JEUBlyyjfx0iFCbi5ssvjXwDaqbaCFIeoMh+TEiQFjIYBX8GgIg/+b9lWUaxGxTdx/mdE8MJOufX3G3df8eXklil2D89R0SfkHqxunbheBp4POXP2w3b7LbKv4NV5pgPSWx1h8Hv60ODQyEcF658EA23sV7W2SAKc/Pt+WQ9fVuP/1ZWFHZN3ACd03pqHI0HLzrIufLE3aww1dKpiZKL1v7Irvai9RbCugEYYX5BzoBF/DTwYDJuH8OFf1H+nNT8oO+LbnYgkZ7POrKQ+8SAuZRIYg708bh5EmDaiS04D2CaBpRV9rfiQwhvHnWY35c6G2BXbGsgU="


# travis-ci runs by default on ancient Ubuntu 12.04 (precise)
# following options will give us Ubuntu 14.04 (trusty)
sudo: required
dist: trusty

addons:
  apt:
    packages:
    - python2.7
    - python-pip-whl
    - python-wxgtk2.8
    - python-wxtools
    - python-wxversion
    - python-wheel
    - python-tk
    - python-pytest


before_install:
  - python -V

install:
  - ./.travis/install_linux.sh

script:
  - ./install_versioneer.sh
  - pip install -r requirements.txt --user
  - py.test
  - if [[ "$TRAVIS_TEST_RESULT" == "0" ]]; then .travis/deploy_package.sh pypi; fi
